import os
from datetime import datetime

from django.conf import settings

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


# Styles

styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER
title_style.spaceAfter = 20

heading_style = styles["Heading2"]
heading_style.spaceBefore = 15
heading_style.spaceAfter = 8

normal_style = styles["BodyText"]
normal_style.spaceAfter = 6

bullet_style = styles["BodyText"]
bullet_style.leftIndent = 15
bullet_style.spaceAfter = 5

# Helper Functions

def clean_text(text):
    """
    Cleans unicode and formatting characters.
    """

    if not text:
        return ""

    text = str(text)

    replacements = {
        "\n": "<br/>",
        "\r": "",
        "\t": " ",
        "■": "",
        "\u25a0": "",
        "\u2022": "•",
        "\xa0": " ",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text



def heading(title):
    return Paragraph(title, heading_style)




def body(text):
    return Paragraph(clean_text(text), normal_style)



def bullet(title, description):

    return [
        Paragraph(
            f"<b>• {clean_text(title)}</b>",
            bullet_style,
        ),
        Paragraph(
            clean_text(description),
            normal_style,
        ),
        Spacer(1, 8),
    ]



def make_table(data):

    table = Table(
        data,
        colWidths=[2.3 * inch, 4.2 * inch],
    )

    table.setStyle(

        TableStyle(

            [

                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("VALIGN", (0, 0), (-1, -1), "TOP"),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

                ("TOPPADDING", (0, 1), (-1, -1), 6),

                ("BOTTOMPADDING", (0, 1), (-1, -1), 6),

            ]

        )

    )

    return table




def add_header_footer(canvas, doc):

    canvas.saveState()

    canvas.setFont("Helvetica-Bold", 15)

    canvas.drawString(
        40,
        810,
        "APK Scanner Security Report",
    )

    canvas.setFont("Helvetica", 9)

    canvas.drawRightString(
        560,
        810,
        datetime.now().strftime("%d-%m-%Y %H:%M"),
    )

    canvas.line(40, 800, 560, 800)

    canvas.line(40, 40, 560, 40)

    canvas.drawString(
        40,
        25,
        "Generated by APK Scanner + MobSF",
    )

    canvas.drawRightString(
        560,
        25,
        f"Page {doc.page}",
    )

    canvas.restoreState()



# Main PDF Function


def generate_pdf(report):

    reports_dir = os.path.join(
        settings.MEDIA_ROOT,
        "reports",
    )

    os.makedirs(
        reports_dir,
        exist_ok=True,
    )

    filename = (
        f"{report.get('app_name')}_"
        f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    )

    pdf_path = os.path.join(
        reports_dir,
        filename,
    )

    doc = SimpleDocTemplate(
        pdf_path,
        topMargin=70,
        bottomMargin=55,
    )

    story = []

   
    # TITLE
   
    story.append(
        Paragraph(
            "MobSF APK Security Report",
            title_style,
        )
    )

    story.append(
        Spacer(1, 0.3 * inch)
    )

   
    # APPLICATION INFORMATION
  

    story.append(
        heading("Application Information")
    )

    info_table = [

        ["Field", "Value"],

        ["Application", report.get("app_name")],

        ["APK", report.get("file_name")],

        ["Version", report.get("version")],

        ["Hash", report.get("hash")],

    ]

    story.append(
        make_table(info_table)
    )

    story.append(
        Spacer(1, 0.25 * inch)
    )

    
    # SECURITY SUMMARY
    

    story.append(
        heading("Security Summary")
    )

    summary_table = [

        ["Metric", "Value"],

        [
            "Security Score",
            str(report.get("security_score")),
        ],

        [
            "Trackers",
            str(report.get("trackers")),
        ],

        [
            "Total Trackers",
            str(report.get("total_trackers")),
        ],

    ]

    story.append(
        make_table(summary_table)
    )

    story.append(
        Spacer(1, 0.3 * inch)
    )

   
    # HIGH FINDINGS
    

    story.append(
        heading("High Severity Findings")
    )

    highs = report.get("high_findings", [])

    if not highs:

        story.append(
            body("No High Severity Findings.")
        )

    else:

        for item in highs:

            story.extend(

                bullet(
                    item.get("title"),
                    item.get("description"),
                )

            )

    story.append(
        PageBreak()
    )
      
    # WARNINGS
    

    story.append(
        heading("Warnings")
    )

    warnings = report.get("warnings", [])

    if not warnings:

        story.append(
            body("No Warnings.")
        )

    else:

        for item in warnings:

            story.extend(

                bullet(
                    item.get("title"),
                    item.get("description"),
                )

            )

    story.append(
        Spacer(1, 0.25 * inch)
    )

   
    # INFORMATIONAL FINDINGS
   

    story.append(
        heading("Informational Findings")
    )

    infos = report.get("info", [])

    if not infos:

        story.append(
            body("No Informational Findings.")
        )

    else:

        for item in infos:

            story.extend(

                bullet(
                    item.get("title"),
                    item.get("description"),
                )

            )

    story.append(
        Spacer(1, 0.25 * inch)
    )

    
    # SECURE FINDINGS
   

    story.append(
        heading("Secure Findings")
    )

    secure = report.get("secure", [])

    if not secure:

        story.append(
            body("No Secure Findings.")
        )

    else:

        for item in secure:

            story.extend(

                bullet(
                    item.get("title"),
                    item.get("description"),
                )

            )

    story.append(
        Spacer(1, 0.25 * inch)
    )

    
    # SECURITY HOTSPOTS
    

    story.append(
        heading("Security Hotspots")
    )

    hotspots = report.get("hotspots", [])

    if not hotspots:

        story.append(
            body("No Security Hotspots.")
        )

    else:

        for item in hotspots:

            story.extend(

                bullet(
                    item.get("title"),
                    item.get("description"),
                )

            )

    story.append(
        PageBreak()
    )

    # EXPORTED COMPONENTS
    

    story.append(
        heading("Exported Components")
    )

    exported = report.get(
        "exported_components",
        {}
    )

    if not exported:

        story.append(
            body("No Exported Components.")
        )

    else:

        component_table = [

            ["Component", "Count"]

        ]

        for key, value in exported.items():

            component_table.append(

                [
                    key.replace("_", " ").title(),
                    str(value)
                ]

            )

        story.append(
            make_table(component_table)
        )

    story.append(
        Spacer(1, 0.30 * inch)
    )

   
    # HARDCODED SECRETS
    

    story.append(
        heading("Hardcoded Secrets")
    )

    secrets = report.get(
        "secrets",
        []
    )

    if not secrets:

        story.append(
            body("No Hardcoded Secrets Found.")
        )

    else:

        for secret in secrets:

            story.append(

                Paragraph(

                    clean_text(secret),

                    bullet_style

                )

            )

    story.append(
        Spacer(1, 0.30 * inch)
    )

    
    # REPORT SUMMARY
    

    story.append(
        heading("Report Summary")
    )

    summary = f"""
    <b>Application:</b> {clean_text(report.get('app_name'))}<br/>
    <b>Version:</b> {clean_text(report.get('version'))}<br/>
    <b>Security Score:</b> {report.get('security_score')}<br/>
    <b>High Findings:</b> {len(report.get('high_findings', []))}<br/>
    <b>Warnings:</b> {len(report.get('warnings', []))}<br/>
    <b>Information Findings:</b> {len(report.get('info', []))}<br/>
    <b>Hotspots:</b> {len(report.get('hotspots', []))}<br/>
    <b>Trackers:</b> {report.get('trackers')} / {report.get('total_trackers')}
    """

    story.append(
        Paragraph(
            summary,
            normal_style,
        )
    )

    story.append(
        Spacer(1, 0.40 * inch)
    )

   
    # BUILD PDF
    

    doc.build(

        story,

        onFirstPage=add_header_footer,

        onLaterPages=add_header_footer,

    )

    return pdf_path