# Generated by Django 6.0.6 on 2026-07-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apk',
            name='hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='apk',
            name='report_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='apk',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apk',
            name='security_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apk',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('SCANNING', 'Scanning'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
